project_id = "yfgywwbchyvtcogdfvvo"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.ai-exercise-demo]
verify_jwt = true

[functions.generate-meal-image]
verify_jwt = false