// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfgywwbchyvtcogdfvvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZ3l3d2JjaHl2dGNvZ2RmdnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODEwMzMsImV4cCI6MjA3MTM1NzAzM30.VKK3USNYfZoQdz3sTJrQH3i-6dlUS97R3WqWAi6DpKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});